title: The Basics of Nuclear Energy

description: By the 2023 Digital Scholarship Summer Fellows at Bryn Mawr College

#author:
  #name: 
  #email: 

github:
  owner_name: digbmc
  repository_name: reactor-jct-jekyll
  source:
    branch: main

nav_pages:
  - _pages/index.md
  - _articles/history.md
  # - _podcasts/index.md
  - _pages/about.md
  - _pages/contact.md

collections:
  articles:
    output: true
    permalink: /:collection/:path/
  podcasts:
    output: true
    permalink: /:collection/:path/
  pages:
    output: true
    permalink: /:collection/:path/
  admin:
    output: true
    permalink: /:collection/:path/
  examples:
    output: true
    permalink: /:collection/:path/

show_excerpts: true
show_rss_feed: true
max-width: 1000px

footer:
  show_github_link: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
