title: Nuclear Power

description: Created by the 2023 [Digital Scholarship Summer Fellows](https://digitalscholarship.blogs.brynmawr.edu/digital-scholarship-summer-fellows-program/) at Bryn Mawr College for the [Reactor Room](https://digitalscholarship.brynmawr.edu/reactor-room/)

#author:
  #name: 
  #email: 

github:
  owner_name: digbmc
  repository_name: reactor-jct-jekyll
  source:
    branch: main

nav_pages:
  - _pages/index.md
  - _articles/nuclear-history.md
  - _articles/science.md

collections:
  articles:
    output: true
    permalink: /:collection/:path/
  pages:
    output: true
    permalink: /:collection/:path/
  admin:
    output: false
    permalink: /:collection/:path/
  examples:
    output: false
    permalink: /:collection/:path/

show_excerpts: true
show_rss_feed: true
max-width: 1000px

footer:
  show_github_link: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
